---
- name: Ensure git and cron are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - cron

- name: Clone letsencrypt sources
  git:
    repo: https://github.com/certbot/certbot
    dest: /opt/letsencrypt
    update: no
    version: "{{ letsencrypt_version }}"

- name: Define certbot bin path
  set_fact:
    letsencrypt_bin: /opt/letsencrypt/certbot-auto

- name: Bootstrap letsencrypt
  command: "{{ letsencrypt_bin }} --version --non-interactive"
  changed_when: false
