---
- name: Ensure certbot ppa repository
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
    update_cache: yes

- name: Install certbot
  package:
    name: "{{ item }}"
    state: present
  loop:
    - cron
    - certbot

- name: Define certbot bin path
  set_fact:
    letsencrypt_bin: /usr/bin/certbot
