---
- name: Attempt to get the certificate using the standalone authenticator
  command: >
    /opt/letsencrypt/letsencrypt-auto certonly
        --agree-tos
        --non-interactive
        --email {{ admin_email }}
        --standalone
        -d {{ letsencrypt_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ letsencrypt_domain_name }}/cert.pem
...
