---
- name: Attempt to get the certificate using the standalone authenticator
  command: >
    {{ letsencrypt_bin }} certonly
        --no-bootstrap
        --agree-tos
        --non-interactive
        --email {{ letsencrypt_email }}
        --standalone
        -d {{ letsencrypt_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ letsencrypt_domain_name }}/cert.pem
...
