---
- name: Ensure git and cron are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - cron

- name: Clone letsencrypt sources
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: /opt/letsencrypt
    update: no
    version: "{{ letsencrypt_version }}"

- name: Install renewal cron
  cron:
    user: root
    name: "Let's Encrypt Renewal"
    weekday: "1"
    hour: "2"
    minute: "30"
    job: "/opt/letsencrypt/letsencrypt-auto renew >> /var/log/letsencrypt-renew.log"

- name: go get fake cert
  import_tasks: dev.yml
  when: letsencrypt_is_dev

- name: Detect if a web server is running on port 80
  wait_for:
    port: 80
    timeout: 1
  ignore_errors: true
  check_mode: no
  register: is_80

- name: Go get letsencrypt's cert (without web server)
  import_tasks: letsencrypt-standalone.yml
  when: not letsencrypt_is_dev and is_80 | failed

- name: Go get letsencrypt's cert (with web server)
  import_tasks: letsencrypt-webroot.yml
  when: not letsencrypt_is_dev and is_80 | succeeded
...
